### ISSUE TITLE
max_timestamp=X_train.shape[-1]

### ISSUE THREAD

**Issue by hushuguo** [JakubBilski/CALIMERA#2]
in CALIMERA.py , max_timestamp=X_train.shape[-1],This Python statement may be incorrect; please take a look at it.

**Comment by JakubBilski** [comment]
Could you provide some more details? The intended purpose of this code is to get the last dimension of the matrix, which should correspond to a single sample's single channel's content, which lemgth (in time series of equal length, which is assumed in Calimera) should correspond to the maximal timestamp.

**Comment by JakubBilski** [comment]
Btw, the code has been tested on multi and univariate datasets from https://www.timeseriesclassification.com/dataset.php

**Comment by hushuguo** [comment]
Sorry about that, I have made a mistake in understanding the code.
The code is correct.
